defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      lang: "en"

languages:
  en:
    description: "Broken Vibe Studios in Rodgau, Germany"
    lang: "en"
  de:
    description: "Broken Vibe Studios in Rodgau, Deutschland"
    lang: "de"

collections:
  en:
    output: true
    permalink: /en/:path/
  de:
    output: true
    permalink: /de/:path/