url: "brokenvibestudios.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Broken Vibe Studios" # the name of your site, e.g. ACME Corp.

defaults:
  #languages
  -
    scope:
      path: ""
    values:
      lang: "en"
      layout: default
  -
    scope:
      path: "de"
    values:
      lang: "de"